name: BotQuest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 git+https://github.com/PyCQA/pyflakes git+https://gitlab.com/PyCQA/pycodestyle
          pip install coverage pylint bandit
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics
      - name: Lint with Pylint
        run: pylint --rcfile=setup.cfg botquest/ tests/ bot.py
      - name: Check Security with Bandit
        run: bandit -r -s B311 botquest/ tests/ bot.py
      - name: Test with unittest and coverage
        run: |
          coverage run --source botquest -m unittest discover
          coverage report -m